### ISSUE TITLE
RayhanADev, You have been summoned

### ISSUE THREAD

**Issue by RayhanADev** [theiocoder/Ping-me#2]
~~There is no reason to this I'm just bored sorry xD~~

**Comment by IcingHackz** [comment]
~~lmfao~~

**Comment by RayhanADev** [comment]
I literally wrote this not too long after they made the repo
> i will try to respond as fast as possible, but if i dont respond for a *while* then just wait pls

lol

**Comment by IcingHackz** [comment]
LOL

**Comment by theiocoder** [comment]
@RayhanADev hello there, i haven't been on this repo, so i didn't notice you made an issue, so *hi* again

**Comment by RayhanADev** [comment]
@theiocoder heya! XD I'm satisfied now so I'll close this :)

**Comment by theiocoder** [comment]
ok lol
