### ISSUE TITLE
i was bored so i did this

### ISSUE THREAD

**Issue by theiocoder** [theiocoder/Ping-me#7]
h i &nbsp;&nbsp; t h e r e

**Comment by iop3** [comment]
b r u h

**Comment by theiocoder** [comment]
> b r u h

w a t
@iop3

**Comment by JBYT27** [comment]
l o l

**Comment by iop3** [comment]
l u l

**Comment by theiocoder** [comment]
![L O L](https://user-images.githubusercontent.com/64909897/120382598-d3b9ad00-c2f1-11eb-8a64-4af7ea4f55e7.png)
l o l

**Comment by theiocoder** [comment]
now im gonna close this issue
